import Foundation

/// Writes typed access code for the exported sounds, so games reference sounds by key instead of paths.
enum CodeGenerator {
    static let godotName = "sounds.gd"
    static let typeScriptName = "sounds.ts"

    // MARK: - Godot

    /// A `Sounds` class with preloaded streams, a lookup by key, variation groups, and loop settings
    /// for OGG/MP3 (which can't store loop points Godot reads). Sprite sounds are web-only and skipped.
    static func godot(_ sounds: [ExportedSound], projectName: String, exportFolder: URL) -> String {
        let playable = sounds.filter { $0.spriteStart == nil }
        guard !playable.isEmpty else { return "" }
        let base = godotResourcePath(for: exportFolder)
        var names = Set<String>()
        var constants: [(key: String, name: String)] = []
        var lines = [
            "# Generated by Game Audio Asset Manager from project \"\(projectName)\". Do not edit; export again instead.",
            "class_name Sounds",
            "extends Object",
            "",
        ]
        for sound in playable {
            var name = identifier(sound.key)
            while names.contains(name) { name += "_" }
            names.insert(name)
            constants.append((sound.key, name))
            lines.append("const \(name) := preload(\"\(base)\(sound.file)\")")
        }

        lines += ["", "## Every sound by key, e.g. Sounds.ALL[\"sfx/jump\"].", "const ALL := {"]
        lines += constants.map { "\t\"\($0.key)\": \($0.name)," }
        lines.append("}")

        let nameByKey = Dictionary(uniqueKeysWithValues: constants.map { ($0.key, $0.name) })
        let groups = ProjectExporter.groups(playable.map(\.key))
        lines += ["", "## Variations of one sound; pick one with Sounds.random(\"sfx/jump\").", "const GROUPS := {"]
        for (group, keys) in groups.sorted(by: { $0.key < $1.key }) {
            lines.append("\t\"\(group)\": [\(keys.compactMap { nameByKey[$0] }.joined(separator: ", "))],")
        }
        lines.append("}")

        let loops = playable.filter { $0.loop != nil && $0.format != .wav }
        if !loops.isEmpty {
            lines += ["", "static func _static_init() -> void:", "\t# OGG and MP3 can't carry loop points, so they are applied here."]
            for sound in loops {
                guard let name = nameByKey[sound.key], let loop = sound.loop else { continue }
                let type = sound.format == .ogg ? "AudioStreamOggVorbis" : "AudioStreamMP3"
                let variable = "stream_\(name.lowercased())"
                lines.append("\tvar \(variable): \(type) = \(name)")
                lines.append("\t\(variable).loop = true")
                lines.append("\t\(variable).loop_offset = \(String(format: "%.3f", loop.start))")
            }
        }

        lines += [
            "",
            "static func get_stream(key: String) -> AudioStream:",
            "\treturn ALL.get(key)",
            "",
            "static func random(group: String) -> AudioStream:",
            "\treturn GROUPS[group].pick_random()",
            "",
        ]
        return lines.joined(separator: "\n")
    }

    /// `res://...` path of the export folder if it sits inside a Godot project, otherwise a
    /// path relative to the generated script (which lives in the export folder).
    static func godotResourcePath(for exportFolder: URL) -> String {
        var folder = exportFolder.standardizedFileURL
        let target = folder.path
        while folder.path != "/" {
            if FileManager.default.fileExists(atPath: folder.appendingPathComponent("project.godot").path) {
                let relative = target.dropFirst(folder.path.count).trimmingCharacters(in: CharacterSet(charactersIn: "/"))
                return "res://" + (relative.isEmpty ? "" : relative + "/")
            }
            folder = folder.deletingLastPathComponent()
        }
        return ""
    }

    /// `sfx/player/jump_01` -> `SFX_PLAYER_JUMP_01`.
    static func identifier(_ key: String) -> String {
        var name = key.uppercased().map { $0.isLetter || $0.isNumber ? String($0) : "_" }.joined()
        while name.contains("__") { name = name.replacingOccurrences(of: "__", with: "_") }
        name = name.trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        if name.first?.isNumber ?? true { name = "SOUND_" + name }
        return name
    }

    // MARK: - TypeScript

    /// A typed map of sounds and groups for three.js; unknown keys fail to compile.
    static func typeScript(_ sounds: [ExportedSound], projectName: String) -> String {
        guard !sounds.isEmpty else { return "" }
        func number(_ value: Double) -> String { String(format: "%.3f", value) }
        var lines = [
            "// Generated by Game Audio Asset Manager from project \"\(projectName)\". Do not edit; export again instead.",
            "// URLs are relative to the export folder; prefix them with where you serve it from.",
            "",
            "export interface SoundInfo {",
            "  url: string;",
            "  duration?: number;",
            "  loop: boolean;",
            "  loopStart?: number;",
            "  loopEnd?: number;",
            "  bpm?: number;",
            "  /** Offset in seconds when the sound lives inside an audio sprite (see *.sprite.json). */",
            "  spriteStart?: number;",
            "}",
            "",
            "export const sounds = {",
        ]
        for sound in sounds {
            var fields = ["url: '\(sound.file)'"]
            if let duration = sound.duration { fields.append("duration: \(number(duration))") }
            fields.append("loop: \(sound.loop != nil)")
            if let loop = sound.loop {
                fields.append("loopStart: \(number(loop.start))")
                fields.append("loopEnd: \(number(loop.end))")
            }
            if let tempo = sound.tempo { fields.append("bpm: \(String(format: "%g", tempo.bpm))") }
            if let start = sound.spriteStart { fields.append("spriteStart: \(number(start))") }
            lines.append("  '\(sound.key)': { \(fields.joined(separator: ", ")) },")
        }
        lines += [
            "} as const satisfies Record<string, SoundInfo>;",
            "",
            "export type SoundKey = keyof typeof sounds;",
            "",
            "export const groups = {",
        ]
        for (group, keys) in ProjectExporter.groups(sounds.map(\.key)).sorted(by: { $0.key < $1.key }) {
            lines.append("  '\(group)': [\(keys.map { "'\($0)'" }.joined(separator: ", "))],")
        }
        lines += [
            "} as const satisfies Record<string, readonly SoundKey[]>;",
            "",
            "export type SoundGroup = keyof typeof groups;",
            "",
            "/** Picks a random variation, e.g. pickVariant('sfx/jump') -> 'sfx/jump_03'. */",
            "export function pickVariant(group: SoundGroup): SoundKey {",
            "  const list: readonly SoundKey[] = groups[group];",
            "  return list[Math.floor(Math.random() * list.length)];",
            "}",
            "",
        ]
        return lines.joined(separator: "\n")
    }
}
