import Foundation

/// Generates `audio_engine.ts`: a small, dependency-free Web Audio engine for the project's
/// events and buses (variant picking, random pitch and volume, instance limits, cooldowns,
/// 3D panning, sprites and loops). It imports the sound table from `sounds.ts`.
enum WebAudioGenerator {
    static let fileName = "audio_engine.ts"

    static func engine(events: [ExportedEvent], buses: [AudioBus], projectName: String) -> String {
        func number(_ value: Double) -> String {
            let rounded = (value * 1000).rounded() / 1000
            return rounded == rounded.rounded() ? String(Int(rounded)) : String(rounded)
        }
        let busLines = Mix.sorted(buses).map { "  { path: '\($0.path)', parent: '\($0.parentPath ?? "Master")', volumeDb: \(number($0.volumeDb)) }," }
        let eventLines = events.filter { !$0.sounds.isEmpty }.map { event -> String in
            let e = event.event
            var fields = [
                "sounds: [\(event.sounds.map { "{ sound: '\($0.sound.key)', weight: \(number($0.weight)) }" }.joined(separator: ", "))]",
                "playback: '\(e.playback.rawValue)'",
                "pitchSemitones: \(number(e.pitchSemitones))",
                "volumeDb: \(number(e.volumeDb))",
                "volumeRandomDb: \(number(e.volumeRandomDb))",
                "bus: '\(e.bus)'",
                "maxInstances: \(e.maxInstances)",
                "cooldownMs: \(number(e.cooldownMs))",
            ]
            if let spatial = e.spatial {
                fields.append("spatial: { attenuation: '\(spatial.attenuation.rawValue)', unitSize: \(number(spatial.unitSize)), maxDistance: \(number(spatial.maxDistance)) }")
            }
            return "  '\(event.key)': { \(fields.joined(separator: ", ")) },"
        }

        return """
        // Generated by Game Audio Asset Manager from project "\(projectName)". Do not edit; export again instead.
        // A small Web Audio engine for this project's sound events and mixer buses. No dependencies.
        //
        //   const engine = new AudioEngine(new AudioContext(), '/audio/');
        //   await engine.load();                 // optional: preload every event's sounds
        //   engine.play('player/jump');          // 2D
        //   engine.play('world/door', { position: [4, 0, -2] });  // 3D, if the event is positional
        //   engine.setListener([0, 1.7, 0], [0, 0, -1]);
        //   engine.setBusVolume('Music', -12);

        import { sounds, type SoundKey, type SoundInfo } from './sounds';

        export type Attenuation = 'inverse' | 'inverseSquare' | 'logarithmic' | 'none';
        export type Playback = 'randomNoRepeat' | 'random' | 'sequence';

        export interface BusInfo {
          path: string;
          parent: string;
          volumeDb: number;
        }

        export interface EventInfo {
          sounds: readonly { sound: SoundKey; weight: number }[];
          playback: Playback;
          pitchSemitones: number;
          volumeDb: number;
          volumeRandomDb: number;
          bus: string;
          maxInstances: number;
          cooldownMs: number;
          spatial?: { attenuation: Attenuation; unitSize: number; maxDistance: number };
        }

        export const buses = [
        \(busLines.joined(separator: "\n"))
        ] as const satisfies readonly BusInfo[];

        export type BusPath = 'Master' | (typeof buses)[number]['path'];

        export const events = {
        \(eventLines.joined(separator: "\n"))
        } as const satisfies Record<string, EventInfo>;

        export type EventKey = keyof typeof events;

        export interface PlayOptions {
          /** World position for positional events. */
          position?: readonly [number, number, number];
          /** Extra volume in dB on top of the event's volume. */
          volumeDb?: number;
        }

        const dbToGain = (db: number): number => Math.pow(10, db / 20);

        export class AudioEngine {
          readonly context: AudioContext;
          private readonly baseUrl: string;
          private readonly busNodes = new Map<string, GainNode>();
          private readonly buffers = new Map<string, Promise<AudioBuffer>>();
          private readonly lastPlayed = new Map<string, number>();
          private readonly lastIndex = new Map<string, number>();
          private readonly active = new Map<string, AudioBufferSourceNode[]>();

          constructor(context: AudioContext, baseUrl = '') {
            this.context = context;
            this.baseUrl = baseUrl;
            const master = new GainNode(context);
            master.connect(context.destination);
            this.busNodes.set('Master', master);
            for (const bus of buses as readonly BusInfo[]) {
              const node = new GainNode(context, { gain: dbToGain(bus.volumeDb) });
              node.connect(this.busNodes.get(bus.parent) ?? master);
              this.busNodes.set(bus.path, node);
            }
          }

          /** Preloads the sounds of the given events (all events by default). */
          async load(keys: readonly EventKey[] = Object.keys(events) as EventKey[]): Promise<void> {
            const urls = new Set<string>();
            for (const key of keys) {
              for (const entry of (events[key] as EventInfo).sounds) urls.add((sounds[entry.sound] as SoundInfo).url);
            }
            await Promise.all([...urls].map((url) => this.buffer(url)));
          }

          setBusVolume(path: BusPath, db: number): void {
            this.busNodes.get(path)?.gain.setTargetAtTime(dbToGain(db), this.context.currentTime, 0.02);
          }

          setListener(
            position: readonly [number, number, number],
            forward: readonly [number, number, number] = [0, 0, -1],
            up: readonly [number, number, number] = [0, 1, 0],
          ): void {
            const listener = this.context.listener;
            const now = this.context.currentTime;
            listener.positionX.setValueAtTime(position[0], now);
            listener.positionY.setValueAtTime(position[1], now);
            listener.positionZ.setValueAtTime(position[2], now);
            listener.forwardX.setValueAtTime(forward[0], now);
            listener.forwardY.setValueAtTime(forward[1], now);
            listener.forwardZ.setValueAtTime(forward[2], now);
            listener.upX.setValueAtTime(up[0], now);
            listener.upY.setValueAtTime(up[1], now);
            listener.upZ.setValueAtTime(up[2], now);
          }

          /** Plays an event. Resolves to the source, or undefined when cooling down. */
          async play(key: EventKey, options: PlayOptions = {}): Promise<AudioBufferSourceNode | undefined> {
            const event = events[key] as EventInfo;
            const now = performance.now();
            if (now - (this.lastPlayed.get(key) ?? -Infinity) < event.cooldownMs) return undefined;
            this.lastPlayed.set(key, now);

            const index = this.pick(key, event);
            if (index === undefined) return undefined;
            const entry = event.sounds[index];
            if (!entry) return undefined;
            const info = sounds[entry.sound] as SoundInfo;
            const buffer = await this.buffer(info.url);

            const playing = this.active.get(key) ?? [];
            while (event.maxInstances > 0 && playing.length >= event.maxInstances) playing.shift()?.stop();

            const source = new AudioBufferSourceNode(this.context, { buffer });
            const pitch = (Math.random() * 2 - 1) * event.pitchSemitones;
            source.playbackRate.value = Math.pow(2, pitch / 12);
            const gain = new GainNode(this.context, {
              gain: dbToGain(event.volumeDb + (options.volumeDb ?? 0) - Math.random() * event.volumeRandomDb),
            });
            source.connect(gain);

            let output: AudioNode = gain;
            if (event.spatial && options.position) {
              const spatial = event.spatial;
              const panner = new PannerNode(this.context, {
                panningModel: 'HRTF',
                distanceModel: spatial.attenuation === 'inverseSquare' ? 'exponential' : 'inverse',
                rolloffFactor: spatial.attenuation === 'none' ? 0 : spatial.attenuation === 'inverseSquare' ? 2 : 1,
                refDistance: spatial.unitSize,
                maxDistance: spatial.maxDistance > 0 ? spatial.maxDistance : 10000,
                positionX: options.position[0],
                positionY: options.position[1],
                positionZ: options.position[2],
              });
              gain.connect(panner);
              output = panner;
            }
            output.connect(this.busNodes.get(event.bus) ?? this.busNodes.get('Master')!);

            if (info.loop && info.loopStart !== undefined && info.loopEnd !== undefined) {
              source.loop = true;
              source.loopStart = (info.spriteStart ?? 0) + info.loopStart;
              source.loopEnd = (info.spriteStart ?? 0) + info.loopEnd;
            }
            if (info.spriteStart !== undefined) {
              source.start(0, info.spriteStart, info.duration);
            } else {
              source.start();
            }

            playing.push(source);
            this.active.set(key, playing);
            source.onended = () => {
              const list = this.active.get(key);
              if (list) list.splice(list.indexOf(source) >>> 0, 1);
            };
            return source;
          }

          /** Stops every playing instance of an event, or of all events. */
          stop(key?: EventKey): void {
            for (const [eventKey, list] of this.active) {
              if (key === undefined || key === eventKey) list.splice(0).forEach((source) => source.stop());
            }
          }

          private pick(key: string, event: EventInfo): number | undefined {
            const count = event.sounds.length;
            if (count === 0) return undefined;
            const last = this.lastIndex.get(key);
            let index: number;
            if (event.playback === 'sequence') {
              index = ((last ?? -1) + 1) % count;
            } else {
              const candidates = [...Array(count).keys()].filter(
                (i) => event.playback !== 'randomNoRepeat' || count === 1 || i !== last,
              );
              const weight = (i: number): number => Math.max(event.sounds[i]?.weight ?? 0, 0);
              const total = candidates.reduce((sum, i) => sum + weight(i), 0);
              let threshold = Math.random() * total;
              index = candidates[candidates.length - 1] ?? 0;
              for (const i of candidates) {
                threshold -= weight(i);
                if (threshold < 0) {
                  index = i;
                  break;
                }
              }
            }
            this.lastIndex.set(key, index);
            return index;
          }

          private buffer(url: string): Promise<AudioBuffer> {
            let pending = this.buffers.get(url);
            if (!pending) {
              pending = fetch(this.baseUrl + url)
                .then((response) => response.arrayBuffer())
                .then((data) => this.context.decodeAudioData(data));
              this.buffers.set(url, pending);
            }
            return pending;
          }
        }

        """
    }
}
